server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://ec2-174-129-29-101.compute-1.amazonaws.com:5432/d9m762m2r16c0q?user=rjnrpjhlchxazn&password=82734bdb9f398ab2051158c897d2d94fd626c45abdf864a0b0fdfabf4c553f43&sslfactory=org.postgresql.ssl.NonValidatingFactory
    platform: postgres
    jpa:
      database: POSTGRESQL
      show-sql: false
      properties:
        hibernate:
          temp:
            use-jdbc-metadata-defaults: false
          jdbc:
            lob:
              non-contextual-creation: true